theme: minimal-mistakes-jekyll
locale: es
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-archives
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate-v2
    - jekyll-avatar
    - jemoji
    - jekyll-mentions
    - jekyll-include-cache

# logo: https://res.cloudinary.com/hectorip/image/upload/c_scale,w_200/v1551590729/TheDojo/dojo-cover_scaodz.jpg
logo: https://res.cloudinary.com/hectorip/image/upload/v1554098427/TheDojo/the-dojo-transparent.png
masthead_title: "The Dojo MX Blog"
title: "The Dojo MX Blog"
words_per_minute: 120

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

author:
  name   : "Héctor Patricio"
  avatar : "/assets/images/me.jpg"
  bio    : "Desarrollador de software, tech lead @ HAL y The Dojo MX"
  uri    : "https://github.com/hectorip"
  home   : https://til.hectorip.com/

analytics:
  provider: "google"
  google:
    tracking_id: "UA-127437335-2"
    anonymize_ip: false # default

comments:
  provider: "disqus"
  disqus:
    shortname: "the-dojo-mx-blog"

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/


include: ["_pages"]
search: true
# minimal_mistakes_skin: neon

pagination:
  enabled: true
  per_page: 25
  permalink: '/:num/'
  title_suffix: ' :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

paginate_path: '/latest/:num'
url: 'https://blog.thedojo.mx'

collections:
  authors:
    output: true
